# Generated by Django 5.1.7 on 2025-04-24 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('librarian', 'Librarian'), ('member', 'Member')], default='member', max_length=20),
        ),
    ]
